version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:3483d157eea398b51c786cc3623482e35efc0be1

workflows:
  checkout-build-publish:
    jobs:         
      - reporting/test_harness:
          command: "pytest --alluredir=allure-results"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
