version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:fd37c94f586957061f165218a32f8002f40ee1bc

workflows:
  checkout-build-publish:
    jobs:         
      - reporting/test_harness:
          command: "pytest --alluredir=allure-results"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
