version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:7198f614c2dea873ba5792256e460864eabd1d8a

workflows:
  checkout-build-publish:
    jobs:         
      - reporting/test_harness:
          command: "pytest --alluredir=allure-results"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
