version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:205c4d1d372362bae0cb63667f50f08a761b549f

workflows:
  checkout-build-publish:
    jobs:         
      - reporting/test_harness:
          command: "pytest --alluredir=allure-results"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
