version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.21

workflows:
  run-test-harness:
    jobs:         
      - reporting/execute_test_harness:
          command: "pytest --alluredir=allure-result"
          test_ready: true
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          notify_slack: true    
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
