version: 2.1

# https://github.com/ministryofjustice/hmpps-reporting-orb/blob/main/src/jobs/execute_test_harness.yml
# https://github.com/ministryofjustice/hmpps-reporting-orb/blob/main/src/scripts/test_harness.sh

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.22

workflows:
  run-test-harness:
    jobs:         
      - reporting/execute_test_harness:
          command: "pytest --alluredir=allure-result"
          test_ready: true
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          notify_slack: false    
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb