version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:32efdc48f5e9716b41894a05b552965040ea892f

workflows:
  checkout-build-publish:
    jobs:         
      - reporting/test_harness:
          command: "pytest --alluredir=allure-results"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
